
development:
  callback_host: payplug-callback.heroku.com
  paypal:
    email:  zeroth_1306867515_biz@gmail.com
    secret: 12345678
  google_checkout:
    merchant_id: "google_checkout_merchant_id"
    merchant_key: "google_checkout_merchant_key"
  amazon_checkout:
    email: "amazon_checkout_sandbox_email"
    secret: "amazon_checkout_sandbox_secret"

production:
  callback_host: ""
  paypal:
    email: "paypal_email"
    secret: "paypal_secret"
  google_checkout:
    merchant_id: "google_checkout_merchant_id"
    merchant_key: "google_checkout_merchant_key"
  amazon_checkout:
    email: "amazon_checkout_sandbox_email"
    secret: "amazon_checkout_sandbox_secret"
